require('./bootstrap');
require('slick-carousel');
require('select2');
require('./navBar');
require('./feedback');
require('./loginRegister');
require('./filterCourses');
require('./coursesDetail');
require('./checked');
